///
/// File generated by cpct_aks2c CPCtelera script
/// Souce file of this conversion: assets/dr07.aks
/// Generation time: lunes, 29 de octubre de 2018, 23:31:09 CET
///

/// Song 'dr_song' metadata macros
#define dr_song_address  0x8000
#define dr_song_size         1623
#define dr_song_end      0x8656

/// Song 'dr_song' array declaration
extern void dr_song[dr_song_size];
