///
/// File generated by cpct_aks2c CPCtelera script
/// Souce file of this conversion: assets/fx02.aks
/// Generation time: lunes, 29 de octubre de 2018, 23:31:08 CET
///

/// Song 'fx_song' metadata macros
#define fx_song_address  0x9000
#define fx_song_size           76
#define fx_song_end      0x904b

/// Song 'fx_song' array declaration
extern void fx_song[fx_song_size];
